Repository TEAM-MODDY/moddy-server, pull requests merged in 2024-01, with the labels that each got.

#16 [feat] CICD 환경 구축
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  Dockerfile
Labels: feat

#13 [feat] 카톡 로그인 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/moddy/server/ServerApplication.java
  src/main/java/com/moddy/server/common/domain/BaseTimeEntity.java
  src/main/java/com/moddy/server/common/exception/enums/SuccessCode.java
  src/main/java/com/moddy/server/controller/auth/dto/request/SocialLoginRequest.java
  src/main/java/com/moddy/server/controller/auth/dto/response/SocialLoginResponse.java
  src/main/java/com/moddy/server/external/kakao/SocialPlatform.java
  src/main/java/com/moddy/server/external/kakao/SocialServiceProvider.java
  src/main/java/com/moddy/server/external/kakao/dto/response/KakaoAccessTokenResponse.java
  src/main/java/com/moddy/server/external/kakao/dto/response/KakaoUserResponse.java
  src/main/java/com/moddy/server/external/kakao/feign/KakaoApiClient.java
  src/main/java/com/moddy/server/external/kakao/feign/KakaoAuthApiClient.java
  src/main/java/com/moddy/server/external/kakao/service/KakaoSocialService.java
  src/main/java/com/moddy/server/external/kakao/service/SocialService.java
Labels: feat

#33 #32 [fix] openfeign 버전 변경
  build.gradle
Labels: fix

#29 #18 [feat] jwt 기능 구현
  build.gradle
  src/main/java/com/moddy/server/common/exception/enums/ErrorCode.java
  src/main/java/com/moddy/server/config/jwt/JwtService.java
Labels: feat

#34 [feat] CORS 관련 config 파일 작성
  src/main/java/com/moddy/server/config/cors/WebConfig.java
Labels: feat

#44 Feat/#43 도메인 작성
  src/main/java/com/moddy/server/domain/BaseTimeEntity.java
  src/main/java/com/moddy/server/domain/day_off/DayOfWeek.java
  src/main/java/com/moddy/server/domain/day_off/DayOff.java
  src/main/java/com/moddy/server/domain/designer/Designer.java
  src/main/java/com/moddy/server/domain/designer/HairShop.java
  src/main/java/com/moddy/server/domain/designer/Portfolio.java
  src/main/java/com/moddy/server/domain/hair_model_application/HairLength.java
  src/main/java/com/moddy/server/domain/hair_model_application/HairModelApplication.java
  src/main/java/com/moddy/server/domain/hair_service_record/HairServiceRecord.java
  src/main/java/com/moddy/server/domain/hair_service_record/ServiceRecord.java
  src/main/java/com/moddy/server/domain/hair_service_record/ServiceRecordTerm.java
  src/main/java/com/moddy/server/domain/har_service_offer/HairServiceOffer.java
  src/main/java/com/moddy/server/domain/prefer_hair_style/HairStyle.java
  src/main/java/com/moddy/server/domain/prefer_hair_style/PreferHairStyle.java
  src/main/java/com/moddy/server/domain/prefer_offer_condition/OfferCondition.java
  src/main/java/com/moddy/server/domain/prefer_offer_condition/PreferOfferCondition.java
  src/main/java/com/moddy/server/domain/prefer_region/PreferRegion.java
  src/main/java/com/moddy/server/domain/region/Region.java
  src/main/java/com/moddy/server/domain/user/Gender.java
  src/main/java/com/moddy/server/domain/user/User.java
Labels: feat

#50 #49 [feat] accessToken, refreshToken 반환 함수
  src/main/java/com/moddy/server/common/dto/TokenPair.java
  src/main/java/com/moddy/server/config/jwt/JwtService.java
Labels: feat

#55 [Feat/#35] 모델뷰 - 메인뷰 조회
  src/main/java/com/moddy/server/common/exception/enums/ErrorCode.java
  src/main/java/com/moddy/server/common/exception/enums/SuccessCode.java
  src/main/java/com/moddy/server/config/WebConfig.java
  src/main/java/com/moddy/server/controller/model/ModelController.java
  src/main/java/com/moddy/server/controller/model/dto/response/ModelMainResponse.java
  src/main/java/com/moddy/server/controller/model/dto/response/OfferResponse.java
  src/main/java/com/moddy/server/domain/designer/Designer.java
  src/main/java/com/moddy/server/domain/designer/HairShop.java
  src/main/java/com/moddy/server/domain/hair_model_application/HairModelApplication.java
  src/main/java/com/moddy/server/domain/hair_model_application/repository/HairModelApplicationJpaRepository.java
  src/main/java/com/moddy/server/domain/hair_service_offer/HairServiceOffer.java
  src/main/java/com/moddy/server/domain/hair_service_offer/repository/HairServiceOfferJpaRepository.java
  src/main/java/com/moddy/server/domain/model/ModelApplyStatus.java
  src/main/java/com/moddy/server/domain/model/repository/ModelJpaRepository.java
  src/main/java/com/moddy/server/domain/prefer_offer_condition/OfferCondition.java
  src/main/java/com/moddy/server/domain/prefer_offer_condition/PreferOfferCondition.java
  src/main/java/com/moddy/server/domain/prefer_offer_condition/repository/PreferOfferConditionJpaRepository.java
  src/main/java/com/moddy/server/domain/user/User.java
  src/main/java/com/moddy/server/service/model/ModelService.java
Labels: feat

#58 #57 [feat] kakao token resolver 추가
  src/main/java/com/moddy/server/config/WebConfig.java
  src/main/java/com/moddy/server/config/resolver/kakao/KakaoCode.java
  src/main/java/com/moddy/server/config/resolver/kakao/KakaoCodeResolver.java
  src/main/java/com/moddy/server/controller/auth/AuthController.java
  src/main/java/com/moddy/server/external/kakao/service/KakaoSocialService.java
Labels: feat

#60 #59 [feat] 유저 마이페이지 조회 기능 구현
  src/main/java/com/moddy/server/common/exception/enums/SuccessCode.java
  src/main/java/com/moddy/server/controller/user/UserController.java
  src/main/java/com/moddy/server/controller/user/dto/response/UserDetailResponseDto.java
  src/main/java/com/moddy/server/service/user/UserService.java
Labels: feat

#62 #61 [docs] 스웨거 명시 수정
  src/main/java/com/moddy/server/controller/auth/AuthController.java
  src/main/java/com/moddy/server/controller/model/ModelController.java
  src/main/java/com/moddy/server/controller/user/UserController.java
Labels: feat

#64 [Feat/#36] 모델 뷰 - 제안 상세보기
  src/main/java/com/moddy/server/common/exception/enums/ErrorCode.java
  src/main/java/com/moddy/server/common/exception/enums/SuccessCode.java
  src/main/java/com/moddy/server/controller/model/ModelController.java
  src/main/java/com/moddy/server/controller/model/dto/response/DesignerInfoResponse.java
  src/main/java/com/moddy/server/controller/model/dto/response/DetailOfferResponse.java
  src/main/java/com/moddy/server/controller/model/dto/response/StyleDetailResponse.java
  src/main/java/com/moddy/server/domain/day_off/DayOff.java
  src/main/java/com/moddy/server/domain/day_off/repository/DayOffJpaRespository.java
  src/main/java/com/moddy/server/domain/designer/repository/DesignerJpaRepository.java
  src/main/java/com/moddy/server/domain/hair_model_application/repository/HairModelApplicationJpaRepository.java
  src/main/java/com/moddy/server/domain/hair_service_offer/repository/HairServiceOfferJpaRepository.java
  src/main/java/com/moddy/server/domain/model/repository/ModelJpaRepository.java
  src/main/java/com/moddy/server/domain/prefer_hair_style/PreferHairStyle.java
  src/main/java/com/moddy/server/domain/prefer_hair_style/repository/PreferHairStyleJpaRepository.java
  src/main/java/com/moddy/server/domain/prefer_offer_condition/repository/PreferOfferConditionJpaRepository.java
  src/main/java/com/moddy/server/service/model/ModelService.java
Labels: feat

#74 #73 [feat] no resource exception handle 추가
  src/main/java/com/moddy/server/common/exception/GlobalControllerExceptionAdvice.java
  src/main/java/com/moddy/server/common/exception/enums/ErrorCode.java
Labels: feat

#70 #67 [feat] 오픈채팅 연결 기능 구현
  src/main/java/com/moddy/server/common/exception/enums/ErrorCode.java
  src/main/java/com/moddy/server/common/exception/enums/SuccessCode.java
  src/main/java/com/moddy/server/controller/designer/DesignerController.java
  src/main/java/com/moddy/server/controller/model/ModelController.java
  src/main/java/com/moddy/server/controller/model/dto/response/DesignerInfoOpenChatResponse.java
  src/main/java/com/moddy/server/controller/model/dto/response/OpenChatResponse.java
  src/main/java/com/moddy/server/domain/designer/repository/DesignerJpaRepository.java
  src/main/java/com/moddy/server/domain/hair_model_application/repository/HairModelApplicationJpaRepository.java
  src/main/java/com/moddy/server/domain/hair_service_offer/HairServiceOffer.java
  src/main/java/com/moddy/server/domain/hair_service_offer/repository/HairServiceOfferJpaRepository.java
  src/main/java/com/moddy/server/domain/model/repository/ModelJpaRepository.java
  src/main/java/com/moddy/server/service/designer/DesignerService.java
  src/main/java/com/moddy/server/service/model/ModelService.java
Labels: feat

#80 #75 [refactor] 디자이너 회원가입 authcontroller로 변경
  src/main/java/com/moddy/server/controller/auth/AuthController.java
  src/main/java/com/moddy/server/controller/designer/DesignerController.java
Labels: fix

#83 #82 [fix] 로깅 시 null 검증 추가
  src/main/java/com/moddy/server/config/aspect/LoggingAspect.java
Labels: fix

#77 [Feat/#56] 모델 회원가입 시 희망 지역 리스트 조회 API
  src/main/java/com/moddy/server/common/exception/enums/SuccessCode.java
  src/main/java/com/moddy/server/controller/auth/AuthController.java
  src/main/java/com/moddy/server/controller/auth/dto/response/RegionResponse.java
  src/main/java/com/moddy/server/domain/prefer_offer_condition/PreferOfferCondition.java
  src/main/java/com/moddy/server/domain/region/Region.java
  src/main/java/com/moddy/server/domain/region/repository/RegionJpaRepository.java
  src/main/java/com/moddy/server/service/auth/AuthService.java
Labels: feat

#85 #84 [fix] kakao id에서 user id로 수정
  src/main/java/com/moddy/server/service/designer/DesignerService.java
Labels: fix

#87 [Feat/#78] 모델 회원가입하기
  src/main/java/com/moddy/server/common/exception/enums/ErrorCode.java
  src/main/java/com/moddy/server/common/exception/enums/SuccessCode.java
  src/main/java/com/moddy/server/controller/auth/AuthController.java
  src/main/java/com/moddy/server/controller/designer/dto/response/UserCreateResponse.java
  src/main/java/com/moddy/server/controller/model/dto/request/ModelCreateRequest.java
  src/main/java/com/moddy/server/domain/hair_service_offer/repository/HairServiceOfferJpaRepository.java
  src/main/java/com/moddy/server/domain/model/Model.java
  src/main/java/com/moddy/server/domain/prefer_region/PreferRegion.java
  src/main/java/com/moddy/server/domain/prefer_region/repository/PreferRegionJpaRepository.java
  src/main/java/com/moddy/server/service/auth/AuthService.java
  src/main/java/com/moddy/server/service/designer/DesignerService.java
  src/main/java/com/moddy/server/service/model/ModelService.java
Labels: feat

#88 #71 [feat] 디자이너 메인 뷰 기능 구현
  src/main/java/com/moddy/server/common/exception/enums/ErrorCode.java
  src/main/java/com/moddy/server/common/exception/enums/SuccessCode.java
  src/main/java/com/moddy/server/controller/designer/DesignerController.java
  src/main/java/com/moddy/server/controller/designer/dto/response/DesignerMainResponse.java
  src/main/java/com/moddy/server/controller/designer/dto/response/HairModelApplicationResponse.java
  src/main/java/com/moddy/server/domain/hair_model_application/repository/HairModelApplicationJpaRepository.java
  src/main/java/com/moddy/server/domain/model/Model.java
  src/main/java/com/moddy/server/domain/model/repository/ModelJpaRepository.java
  src/main/java/com/moddy/server/domain/prefer_hair_style/repository/PreferHairStyleJpaRepository.java
  src/main/java/com/moddy/server/domain/user/User.java
  src/main/java/com/moddy/server/service/designer/DesignerService.java
  src/main/java/com/moddy/server/service/model/ModelService.java
Labels: feat

#93 #90 [feat] 모델 지원서 상세보기 기능 구현
  src/main/java/com/moddy/server/common/exception/enums/SuccessCode.java
  src/main/java/com/moddy/server/controller/designer/DesignerController.java
  src/main/java/com/moddy/server/controller/designer/dto/response/ApplicationDetailInfoResponse.java
  src/main/java/com/moddy/server/controller/designer/dto/response/ApplicationInfoResponse.java
  src/main/java/com/moddy/server/controller/designer/dto/response/HairRecordResponse.java
  src/main/java/com/moddy/server/controller/designer/dto/response/ModelInfoResponse.java
  src/main/java/com/moddy/server/controller/model/dto/response/ApplicationDetailResponse.java
  src/main/java/com/moddy/server/controller/model/dto/response/OpenChatResponse.java
  src/main/java/com/moddy/server/domain/day_off/DayOfWeek.java
  src/main/java/com/moddy/server/domain/hair_service_record/HairServiceRecord.java
  src/main/java/com/moddy/server/domain/hair_service_record/repository/HairServcieRecordJpaRepository.java
  src/main/java/com/moddy/server/domain/prefer_region/repository/PreferRegionJpaRepository.java
  src/main/java/com/moddy/server/domain/user/Gender.java
  src/main/java/com/moddy/server/service/designer/DesignerService.java
Labels: feat

#95 #94 [feat] 제안서 작성하기 기능 구현
  src/main/java/com/moddy/server/common/exception/enums/SuccessCode.java
  src/main/java/com/moddy/server/controller/auth/AuthController.java
  src/main/java/com/moddy/server/controller/designer/DesignerController.java
  src/main/java/com/moddy/server/controller/designer/dto/request/OfferCreateRequest.java
  src/main/java/com/moddy/server/domain/hair_service_offer/HairServiceOffer.java
  src/main/java/com/moddy/server/domain/prefer_offer_condition/PreferOfferCondition.java
  src/main/java/com/moddy/server/service/designer/DesignerService.java
Labels: feat

#100 #98 #89 [feat] sms 전송 기능 구현 및 휴대폰 인증 api 기능 구현
  build.gradle
  src/main/java/com/moddy/server/common/dto/SuccessNonDataResponse.java
  src/main/java/com/moddy/server/common/exception/enums/SuccessCode.java
  src/main/java/com/moddy/server/common/util/SmsUtil.java
  src/main/java/com/moddy/server/config/sms/AwsSnsConfig.java
  src/main/java/com/moddy/server/controller/auth/AuthController.java
  src/main/java/com/moddy/server/controller/auth/dto/request/PhoneNumberRequestDto.java
  src/main/java/com/moddy/server/domain/verify/UserVerification.java
  src/main/java/com/moddy/server/domain/verify/repository/UserVerificationRepository.java
  src/main/java/com/moddy/server/external/sms/SmsService.java
  src/main/java/com/moddy/server/external/sms/impl/AwsSmsServiceImpl.java
  src/main/java/com/moddy/server/service/auth/AuthService.java
Labels: feat

#112 #110 [feat] offer 가 있으면 isSend true 기능 구현
  src/main/java/com/moddy/server/domain/hair_model_application/HairModelApplication.java
  src/main/java/com/moddy/server/domain/hair_service_offer/repository/HairServiceOfferJpaRepository.java
  src/main/java/com/moddy/server/service/designer/DesignerService.java
Labels: feat

#107 #92 [feat] 로그아웃 api 기능 구현
  src/main/java/com/moddy/server/common/exception/enums/SuccessCode.java
  src/main/java/com/moddy/server/controller/auth/AuthController.java
  src/main/java/com/moddy/server/service/auth/AuthService.java
Labels: feat

#102 [Feat/#79] 모델 지원서 작성 API
  src/main/java/com/moddy/server/common/exception/enums/ErrorCode.java
  src/main/java/com/moddy/server/common/exception/enums/SuccessCode.java
  src/main/java/com/moddy/server/controller/designer/dto/request/DesignerCreateRequest.java
  src/main/java/com/moddy/server/controller/model/ModelController.java
  src/main/java/com/moddy/server/controller/model/dto/request/ModelApplicationRequest.java
  src/main/java/com/moddy/server/controller/model/dto/request/ModelHairServiceRequest.java
  src/main/java/com/moddy/server/controller/model/dto/requestEditor/ListPropertyEditor.java
  src/main/java/com/moddy/server/domain/hair_model_application/HairLength.java
  src/main/java/com/moddy/server/domain/hair_model_application/HairModelApplication.java
  src/main/java/com/moddy/server/domain/hair_service_record/HairServiceRecord.java
  src/main/java/com/moddy/server/domain/hair_service_record/ServiceRecord.java
  src/main/java/com/moddy/server/domain/hair_service_record/ServiceRecordTerm.java
  src/main/java/com/moddy/server/domain/hair_service_record/repository/HairServiceRecordJpaRepository.java
  src/main/java/com/moddy/server/domain/prefer_hair_style/HairStyle.java
  src/main/java/com/moddy/server/domain/prefer_hair_style/PreferHairStyle.java
  src/main/java/com/moddy/server/service/model/ModelService.java
Labels: feat

#111 [Fix/#109] 모델 메인뷰에서 상세보기 할시에, isClicked true 처리
  src/main/java/com/moddy/server/domain/hair_service_offer/HairServiceOffer.java
  src/main/java/com/moddy/server/service/model/ModelService.java
Labels: fix

#108 #105 [refactor] multipart/form을 file 과 json으로 분리
  src/main/java/com/moddy/server/config/swagger/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/moddy/server/controller/auth/AuthController.java
  src/main/java/com/moddy/server/controller/designer/dto/HairShopDTO.java
  src/main/java/com/moddy/server/controller/designer/dto/PortfolioDTO.java
  src/main/java/com/moddy/server/controller/designer/dto/request/DesignerCreateRequest.java
  src/main/java/com/moddy/server/controller/designer/dto/response/ModelInfoResponse.java
  src/main/java/com/moddy/server/service/designer/DesignerService.java
Labels: refactor

#113 [Feat/#104] 모델 회원가입 시 디폴트 이미지 저장
  src/main/java/com/moddy/server/controller/model/dto/response/StyleDetailResponse.java
  src/main/java/com/moddy/server/external/s3/S3Service.java
  src/main/java/com/moddy/server/service/model/ModelService.java
Labels: feat

#114 #106 [docs] README 수정
  README.md
Labels: docs

#119 #116 [feat] 로그인 api 리팩토링
  src/main/java/com/moddy/server/common/dto/ErrorDataResponse.java
  src/main/java/com/moddy/server/common/exception/GlobalControllerExceptionAdvice.java
  src/main/java/com/moddy/server/common/exception/model/NotFoundUserException.java
  src/main/java/com/moddy/server/domain/user/User.java
  src/main/java/com/moddy/server/service/auth/AuthService.java
Labels: feat

#125 #86 [feat] 회원 탈퇴하기 api 구현
  src/main/java/com/moddy/server/common/exception/enums/SuccessCode.java
  src/main/java/com/moddy/server/controller/user/UserController.java
  src/main/java/com/moddy/server/domain/day_off/repository/DayOffJpaRepository.java
  src/main/java/com/moddy/server/domain/hair_model_application/repository/HairModelApplicationJpaRepository.java
  src/main/java/com/moddy/server/domain/hair_service_offer/repository/HairServiceOfferJpaRepository.java
  src/main/java/com/moddy/server/domain/hair_service_record/repository/HairServiceRecordJpaRepository.java
  src/main/java/com/moddy/server/domain/prefer_hair_style/repository/PreferHairStyleJpaRepository.java
  src/main/java/com/moddy/server/domain/prefer_offer_condition/repository/PreferOfferConditionJpaRepository.java
  src/main/java/com/moddy/server/domain/prefer_region/repository/PreferRegionJpaRepository.java
  src/main/java/com/moddy/server/service/user/UserService.java
Labels: feat

#123 #122 [feat] 디자이너 상세 보기 API, 머리 기장 상수 변환하는 과정 추가
  src/main/java/com/moddy/server/controller/designer/dto/response/ApplicationInfoResponse.java
  src/main/java/com/moddy/server/service/designer/DesignerService.java
Labels: feat

#128 #124 [fix] designer 저장을 model 저장으로 바꾸기
  src/main/java/com/moddy/server/service/designer/DesignerService.java
Labels: fix

#129 #127 [feat] 모델/디자이너 메인뷰 페이징에 전체 Elements 추가
  src/main/java/com/moddy/server/controller/designer/dto/response/DesignerMainResponse.java
  src/main/java/com/moddy/server/controller/model/dto/response/ModelMainResponse.java
  src/main/java/com/moddy/server/service/designer/DesignerService.java
  src/main/java/com/moddy/server/service/model/ModelService.java
Labels: feat

#130 #126 [feat] 다른 타입의 값이 들어왔을 때 에러 수집 기능 추가
  src/main/java/com/moddy/server/common/exception/GlobalControllerExceptionAdvice.java
  src/main/java/com/moddy/server/common/exception/enums/ErrorCode.java
Labels: feat

#134 #131 [fix] request Body가 있을 경우 @Schema로 예시값 적기
  src/main/java/com/moddy/server/controller/model/dto/request/ModelApplicationRequest.java
  src/main/java/com/moddy/server/controller/model/dto/request/ModelCreateRequest.java
Labels: fix

#120 #118 [fix] 디자이너 회원가입 api 수정
  src/main/java/com/moddy/server/controller/auth/AuthController.java
  src/main/java/com/moddy/server/controller/designer/dto/HairShopDTO.java
  src/main/java/com/moddy/server/controller/designer/dto/HairShopDto.java
  src/main/java/com/moddy/server/controller/designer/dto/PortfolioDTO.java
  src/main/java/com/moddy/server/controller/designer/dto/PortfolioDto.java
  src/main/java/com/moddy/server/controller/designer/dto/request/DesignerCreateRequest.java
  src/main/java/com/moddy/server/domain/designer/Designer.java
  src/main/java/com/moddy/server/domain/designer/repository/DesignerJpaRepository.java
  src/main/java/com/moddy/server/domain/user/User.java
  src/main/java/com/moddy/server/service/designer/DesignerService.java
Labels: fix

#136 #135 [fix] 함수명 리팩토링 && [GET메소드] ENUM return을 value 값으로 변경
  src/main/java/com/moddy/server/controller/auth/AuthController.java
  src/main/java/com/moddy/server/controller/designer/DesignerController.java
  src/main/java/com/moddy/server/controller/designer/dto/response/HairModelApplicationResponse.java
  src/main/java/com/moddy/server/controller/model/ModelController.java
  src/main/java/com/moddy/server/controller/model/dto/response/DesignerInfoResponse.java
  src/main/java/com/moddy/server/controller/model/dto/response/OfferResponse.java
  src/main/java/com/moddy/server/domain/designer/repository/DesignerJpaRepository.java
  src/main/java/com/moddy/server/service/designer/DesignerService.java
  src/main/java/com/moddy/server/service/model/ModelService.java
Labels: fix

#139 #137 [feat] erd user 에서 model로 수정
  src/main/java/com/moddy/server/domain/day_off/DayOff.java
  src/main/java/com/moddy/server/domain/hair_model_application/HairModelApplication.java
  src/main/java/com/moddy/server/domain/hair_model_application/repository/HairModelApplicationJpaRepository.java
  src/main/java/com/moddy/server/domain/hair_service_offer/HairServiceOffer.java
  src/main/java/com/moddy/server/domain/hair_service_offer/repository/HairServiceOfferJpaRepository.java
  src/main/java/com/moddy/server/domain/prefer_region/PreferRegion.java
  src/main/java/com/moddy/server/domain/prefer_region/repository/PreferRegionJpaRepository.java
  src/main/java/com/moddy/server/service/designer/DesignerService.java
  src/main/java/com/moddy/server/service/model/ModelService.java
  src/main/java/com/moddy/server/service/user/UserService.java
Labels: fix

#121 #117 [fix] 모델 회원가입 로직 변경
  src/main/java/com/moddy/server/controller/auth/AuthController.java
  src/main/java/com/moddy/server/controller/designer/DesignerController.java
  src/main/java/com/moddy/server/controller/designer/dto/response/HairModelApplicationResponse.java
  src/main/java/com/moddy/server/controller/model/ModelController.java
  src/main/java/com/moddy/server/domain/designer/Designer.java
  src/main/java/com/moddy/server/domain/designer/repository/DesignerJpaRepository.java
  src/main/java/com/moddy/server/domain/model/Model.java
  src/main/java/com/moddy/server/domain/model/repository/ModelJpaRepository.java
  src/main/java/com/moddy/server/domain/user/User.java
  src/main/java/com/moddy/server/service/model/ModelService.java
Labels: fix

#142 #140 [fix] getAge 함수 user -> model 로 도메인 변경
  src/main/java/com/moddy/server/domain/day_off/DayOfWeek.java
  src/main/java/com/moddy/server/domain/model/Model.java
  src/main/java/com/moddy/server/domain/user/User.java
  src/main/java/com/moddy/server/service/designer/DesignerService.java
Labels: fix

#159 #158 [feat] 이미지 다운로드 링크 전달 API 구현
  src/main/java/com/moddy/server/common/exception/enums/SuccessCode.java
  src/main/java/com/moddy/server/controller/designer/DesignerController.java
  src/main/java/com/moddy/server/controller/designer/dto/request/OfferImageUrlRequestDto.java
  src/main/java/com/moddy/server/controller/designer/dto/response/DownloadUrlResponseDto.java
  src/main/java/com/moddy/server/external/s3/S3Service.java
  src/main/java/com/moddy/server/service/designer/DesignerService.java
  src/main/java/com/moddy/server/service/user/UserService.java
Labels: feat

#157 #155 [fix] Content Type, Json 으로 나눠서 받을 수 있도록 API 수정
  src/main/java/com/moddy/server/controller/model/ModelController.java
  src/main/java/com/moddy/server/controller/model/dto/request/ModelApplicationRequest.java
  src/main/java/com/moddy/server/controller/model/dto/request/ModelHairServiceRequest.java
  src/main/java/com/moddy/server/controller/model/dto/requestEditor/ListPropertyEditor.java
  src/main/java/com/moddy/server/domain/day_off/DayOfWeek.java
  src/main/java/com/moddy/server/domain/hair_model_application/HairLength.java
  src/main/java/com/moddy/server/domain/hair_service_record/ServiceRecord.java
  src/main/java/com/moddy/server/domain/hair_service_record/ServiceRecordTerm.java
  src/main/java/com/moddy/server/domain/prefer_hair_style/HairStyle.java
  src/main/java/com/moddy/server/domain/user/Gender.java
  src/main/java/com/moddy/server/service/model/ModelService.java
Labels: fix

#162 #161 [feat] 신청서 최종 작성 시 유저 정보 불러오는 api 구현
  src/main/java/com/moddy/server/controller/model/ModelController.java
  src/main/java/com/moddy/server/controller/model/dto/response/ApplicationUserDetailResponse.java
  src/main/java/com/moddy/server/service/model/ModelService.java
Labels: feat

#148 #143 [feat] 모델 회원가입 Validation
  src/main/java/com/moddy/server/common/exception/GlobalControllerExceptionAdvice.java
  src/main/java/com/moddy/server/common/validation/prefer_regions/PreferRegionsValidator.java
  src/main/java/com/moddy/server/common/validation/prefer_regions/ValidPreferRegions.java
  src/main/java/com/moddy/server/common/validation/year/ValidYear.java
  src/main/java/com/moddy/server/common/validation/year/YearValidator.java
  src/main/java/com/moddy/server/controller/auth/AuthController.java
  src/main/java/com/moddy/server/controller/model/dto/request/ModelCreateRequest.java
  src/main/java/com/moddy/server/service/model/ModelService.java
Labels: feat

#160 #152 [feat] 전화번호 인증 api 유효성 검사 추가
  src/main/java/com/moddy/server/controller/auth/AuthController.java
  src/main/java/com/moddy/server/controller/auth/dto/request/PhoneNumberRequestDto.java
  src/main/java/com/moddy/server/controller/auth/dto/request/VerifyCodeRequestDto.java
  src/main/java/com/moddy/server/external/sms/SmsService.java
Labels: feat

#163 #149 [feat] 지원서 작성 Validation
  src/main/java/com/moddy/server/common/exception/GlobalControllerExceptionAdvice.java
  src/main/java/com/moddy/server/common/validation/prefer_hair_style/PreferHairStylesValidator.java
  src/main/java/com/moddy/server/common/validation/prefer_hair_style/ValidPreferHairStyles.java
  src/main/java/com/moddy/server/controller/model/ModelController.java
  src/main/java/com/moddy/server/controller/model/dto/request/ModelApplicationRequest.java
  src/main/java/com/moddy/server/controller/model/dto/request/ModelHairServiceRequest.java
Labels: feat

#170 #168 [fix] instagramId 공백 허용 정규식 변경
  src/main/java/com/moddy/server/controller/model/dto/request/ModelApplicationRequest.java
Labels: fix

#167 #166 [fix] 지원서 상세보기 뷰에서 제안서를 보냈으면 isSend = true
  src/main/java/com/moddy/server/service/designer/DesignerService.java
Labels: fix

#169 #164 [fix] 디자이너 메인뷰에서 model 이미지를 지원서 이미지로 수정
  src/main/java/com/moddy/server/service/designer/DesignerService.java
Labels: fix

#172 #171 [fix] 카카오톡 오픈채팅방 링크 API, Application 조회시, offerID -> applicationID로 변경
  src/main/java/com/moddy/server/service/model/ModelService.java
Labels: fix

#174 #173 [fix] URL 어떤 문자든지 (공백 포함) 0번 이상
  src/main/java/com/moddy/server/controller/designer/dto/PortfolioDto.java
Labels: fix

#177 #176 [fix] ENUM 순서 변경
  src/main/java/com/moddy/server/domain/prefer_offer_condition/OfferCondition.java
Labels: fix

#179 #165 [feat] 디자이너가 모델에게 제안할 때 모델에게 sms 전송
  src/main/java/com/moddy/server/common/util/SmsUtil.java
  src/main/java/com/moddy/server/controller/designer/DesignerController.java
  src/main/java/com/moddy/server/external/sms/SmsService.java
  src/main/java/com/moddy/server/external/sms/impl/GabiaSmsServiceImpl.java
  src/main/java/com/moddy/server/service/designer/DesignerService.java
Labels: feat

#183 #182 [fix] 지원서 상세보기 model-> designer
  src/main/java/com/moddy/server/domain/hair_service_offer/repository/HairServiceOfferJpaRepository.java
  src/main/java/com/moddy/server/service/designer/DesignerService.java
Labels: fix

#184 #180 [fix] ErrorCode message 수정및 추가
  src/main/java/com/moddy/server/common/exception/enums/ErrorCode.java
  src/main/java/com/moddy/server/common/validation/year/ValidYear.java
  src/main/java/com/moddy/server/controller/model/dto/request/ModelCreateRequest.java
Labels: fix

#191 #190 [fix] 시연을 위한 Validation 조건 완화
  src/main/java/com/moddy/server/controller/designer/dto/HairShopDto.java
  src/main/java/com/moddy/server/controller/designer/dto/PortfolioDto.java
  src/main/java/com/moddy/server/controller/designer/dto/request/DesignerCreateRequest.java
  src/main/java/com/moddy/server/controller/designer/dto/request/OfferCreateRequest.java
  src/main/java/com/moddy/server/controller/model/dto/request/ModelApplicationRequest.java
  src/main/java/com/moddy/server/controller/model/dto/request/ModelCreateRequest.java
Labels: fix

#195 #194 [feat] Redis 적용 및 번호 인증 로직 수정
  build.gradle
  src/main/java/com/moddy/server/common/util/SmsUtil.java
  src/main/java/com/moddy/server/config/redis/RedisConfig.java
  src/main/java/com/moddy/server/domain/verify/UserVerification.java
  src/main/java/com/moddy/server/domain/verify/repository/UserVerificationRepository.java
  src/main/java/com/moddy/server/service/auth/AuthService.java
Labels: feat

#196 #193 [feat] 회원 탈퇴 시 이미지 삭제 로직 추가
  src/main/java/com/moddy/server/external/s3/S3Service.java
  src/main/java/com/moddy/server/service/designer/DesignerService.java
  src/main/java/com/moddy/server/service/user/UserService.java
Labels: feat

#203 #202 [refactor] 유저 탈퇴 로직 서비스 분리
  src/main/java/com/moddy/server/controller/user/UserController.java
  src/main/java/com/moddy/server/controller/user/UserRegisterController.java
  src/main/java/com/moddy/server/service/application/HairModelApplicationRegisterService.java
  src/main/java/com/moddy/server/service/designer/DesignerRegisterService.java
  src/main/java/com/moddy/server/service/model/ModelRegisterService.java
  src/main/java/com/moddy/server/service/offer/HairServiceOfferRegisterService.java
  src/main/java/com/moddy/server/service/user/UserRegisterService.java
  src/main/java/com/moddy/server/service/user/UserService.java
Labels: refactor

#201 #200 [refactor] 마이페이지 유저 정보 api 분리
  src/main/java/com/moddy/server/controller/user/UserController.java
  src/main/java/com/moddy/server/controller/user/UserRetrieveController.java
  src/main/java/com/moddy/server/service/user/UserRetrieveService.java
  src/main/java/com/moddy/server/service/user/UserService.java
Labels: refactor

#205 #204 [feat] 배포 / 개발 서버 분리
  .github/workflows/dev-cd.yml
  .github/workflows/dev-ci.yml
  .github/workflows/pord-cd.yml
  .github/workflows/prod-ci.yml
Labels: feat

#212 [refactor] 카카오 오픈채팅 api service 분리
  src/main/java/com/moddy/server/controller/model/ModelController.java
  src/main/java/com/moddy/server/controller/model/dto/DesignerInfoOpenChatDto.java
  src/main/java/com/moddy/server/service/application/HairModelApplicationRetrieveService.java
  src/main/java/com/moddy/server/service/designer/DesignerRetrieveService.java
  src/main/java/com/moddy/server/service/model/ModelService.java
  src/main/java/com/moddy/server/service/offer/HairServiceOfferRetrieveService.java
Labels: refactor

#208 #207 개발 서버에서는 인증 번호를 디스코드로 전송하는 기능 구현
  .github/workflows/dev-cd.yml
  .github/workflows/pord-cd.yml
  Dockerfile-Dev
  Dockerfile-Prod
  src/main/java/com/moddy/server/external/sms/impl/DiscordSmsServiceImpl.java
  src/main/java/com/moddy/server/external/sms/impl/GabiaSmsServiceImpl.java
Labels: feat

#214 #213[refactor] 디자이너 메인뷰 api service 분리
  src/main/java/com/moddy/server/controller/designer/DesignerController.java
  src/main/java/com/moddy/server/controller/model/dto/ApplicationModelInfoDto.java
  src/main/java/com/moddy/server/service/application/HairModelApplicationRetrieveService.java
  src/main/java/com/moddy/server/service/designer/DesignerRetrieveService.java
  src/main/java/com/moddy/server/service/designer/DesignerService.java
  src/main/java/com/moddy/server/service/model/ModelRetrieveService.java
Labels: refactor

#222 #218 [Refactor] 모델 회원가입 시 지역 조회 하는 API Controller, Service 분리
  src/main/java/com/moddy/server/controller/auth/AuthController.java
  src/main/java/com/moddy/server/controller/model/ModelController.java
  src/main/java/com/moddy/server/service/auth/AuthService.java
  src/main/java/com/moddy/server/service/model/ModelRetrieveService.java
Labels: refactor

#217 #198 [Refactor] 모델 회원가입 API Service 분리
  build.gradle
  src/main/java/com/moddy/server/common/exception/enums/ErrorCode.java
  src/main/java/com/moddy/server/controller/auth/AuthController.java
  src/main/java/com/moddy/server/controller/model/ModelController.java
  src/main/java/com/moddy/server/controller/model/dto/request/ModelCreateRequest.java
  src/main/java/com/moddy/server/controller/user/dto/UserUpdateDto.java
  src/main/java/com/moddy/server/domain/prefer_region/PreferRegion.java
  src/main/java/com/moddy/server/service/model/ModelRegisterService.java
  src/main/java/com/moddy/server/service/model/ModelService.java
Labels: refactor
